language: node_js
node_js:
  - "18"
services:
  - docker

before_install:
  - npm install

script:
  - npm run build
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t marinmarin/marinmarin-blog:latest .
  - docker push marinmarin/marinmarin-blog:latest
