version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:latest
    working_directory: /home/docker-demo
    steps:
      - checkout
      - run: 
          name: before-install
          command: |
             sudo npm install -g npm
             npm install
      - save_cache:
        key: v1-dependencies-{{ checksum "package.json" }}
        paths:
          - node_modules
      - run: 
          name: buildup
          command: |
            npm run build
            echo '打包开始'
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: docker-build
          command: |
            docker build -t marinmarin/marinmarin-blog:latest
            docker push marinmarin/marinmarin-blog:latest
