version: 2.1
jobs:
  build:
    docker:
      - image: alpine:3.15
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
            npm run build
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker build -t marinmarin/marinmarin-blog:latest .
            docker push marinmarin/marinmarin-blog:latest
